name: ok run now

on:
  schedule:
  - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: ok install deps ????
        run: python -m pip install --upgrade pip requests
				
      - name: pip install crap 
        run: pip install -r requirements.txt

      - name: run crap
        run: python script.py
